<link rel="stylesheet" href="style.css">
<h1> 异常处理 </h1>
<h2> 1 异常概述 </h2>
<h3> 1.1 异常类 </h3>

  - Java 异常类型结构
    <div class=mermaid>
    classDiagram
        Throwable <|-- Error
        Throwable <|-- Exception
        Exception <|-- IOException
        Exception <|-- RuntimeException
    </div>

<h3> 1.2 异常类说明 </h3>
<h4> Error 类 </h4>

  - 系统错误类，代表程序运行时 Java 系统内部错误，通常由硬件或操作系统引发，程序员没法解决
<h4> Exception 类 </h4>

  - 异常类，表示的错误往往是因算法考虑不周或由于编程过程错误引起

<h4> RuntimeException 类 </h4>

  - Java 程序运行时产生的异常，如数组下标越界，对象类型强制转换错，空指针
<h4> IOException 类 </h4>

  - 各种 I/O 错误

<h3> 1.3 异常类型 </h3>
<h4> Checked 异常 </h4>

  - 必须要检查的
  - 编译器在编译程序时检查，否则无法通过
  - 可以用 try 捕捉或 throws 抛出

<h4> Runtime 异常 </h4>

  - 运行时异常
  - 编译器对这类异常不做检查
  - Error 和 RuntimeException 类及其子类实例时 Runtime 异常

<h2> 2 异常处理机制 </h2>
<h3> 2.1 异常的捕获与处理 </h3>
<h4> 异常处理语句 </h4>

  - try-catch-finally 语句
    ```java
    try{
        // 可能会产生异常的程序代码
    }catch(Exception_1 e1){
        // 处理异常 Exception_1 的代码
    }catch(Exception_2 e2){
        // 处理异常 Exception_2 的代码
    }finally{
        // 通常用来释放资源
    }
    ```
  - catch 和 finally 都是可以默认的，但 Java 规范不允许两者同时默认
  - try 语句发现异常后会跳转到对应的 catch 语句，且不再执行其他 catch 语句

<h4> 语句块解释 </h4>

  - try 语句块
    - 程序正常运行下应该要完成的功能，在执行过程中可能会抛出一种或几种类型的异常对象
    - try 语句块后通常跟 0 或多个 catch 语句块，最多一个 finally 语句块
  - catch 语句块
    - 异常发生时，程序终止当前流程，根据获取异常的类型去执行相应的 catch 语句块
    - catch 语句中可以使用异常对象的一些方法来获取信息
      - getMessage(): 用来得到有关异常事件的信息
      - printStackTrace(): 用来跟踪异常事件发生时执行堆栈的内容
    - Java 7 以后的 catch 语句允许使用 "|" 捕获多种异常
  - finally 语句块
    - 无论 try 语句块是否抛出异常，finally 语句块都要被执行

<h3> 2.2 声明抛出异常子句 </h3>
<h4> throw 语句 </h4>

  - 声明抛出异常是一个子句，只能加在方法头部的后面
    ```java
    throws <异常列表>
    ````
  - 举例
    ```java
    public int read() throws IOException{...}
    ```

<h3> 2.3 抛出异常 </h3>
<h4> 抛出异常语句 </h4>

  - 语法格式
    ```java
    throw <异常对象>;
    ```
  - 其中，<异常对象>必须是 Throwable 类或其子类的对象
    ```java
    throw new Exception("这是一个异常对象")
    ```

<h2> 3 自定义异常类型 </h2>
<h3> 3.1 自定义异常 </h3>
<h4> 基本概念 </h4>

  - 自定义异常必须是 Throwable 类的子类，通常是 Exception 类或其子类继承